import { ArrowDown, ArrowRight, Code2, Database, Globe2, Github, Layers3, Monitor, Server } from 'lucide-react';

export function ArchitectureDiagram() {
  return <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-[0_15px_55px_rgba(16,44,66,.07)] sm:p-7">
    <div className="grid gap-8 md:grid-cols-[1fr_auto_1fr] md:items-stretch">
      <section aria-labelledby="desktop-flow-title" className="rounded-2xl bg-slate-950 p-5 text-white sm:p-6">
        <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-teal-700"><Monitor size={19} aria-hidden="true"/></span><div><h2 id="desktop-flow-title" className="text-sm font-bold">Hospital desktop application</h2><p className="text-[9px] text-slate-400">Primary operational product</p></div></div>
        <div className="mt-6 grid gap-2">{[[Code2,'Java Swing + FlatLaf','Java 17+ · Maven'],[Layers3,'Service and DAO layers','Target architecture'],[Database,'JDBC connection','PostgreSQL JDBC · target']].map(([Icon,title,sub],index)=>{const Component=Icon as typeof Code2;return <div key={String(title)} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] p-3"><span className="grid size-8 place-items-center rounded-lg bg-white/5 text-teal-200"><Component size={16}/></span><span className="flex-1"><b className="block text-[11px]">{String(title)}</b><small className="mt-0.5 block text-[9px] text-slate-400">{String(sub)}</small></span><span className="text-[8px] text-slate-600">0{index+1}</span></div>;})}</div>
        <div className="my-4 flex items-center justify-center gap-2 text-[9px] text-slate-400"><span className="h-px flex-1 bg-white/10"/><ArrowDown size={13}/><span className="h-px flex-1 bg-white/10"/></div>
        <div className="flex items-center gap-3 rounded-xl bg-teal-50 p-3 text-slate-900"><span className="grid size-8 place-items-center rounded-lg bg-white text-teal-800"><Database size={16}/></span><span className="flex-1"><b className="block text-[11px]">PostgreSQL / Supabase</b><small className="mt-0.5 block text-[9px] text-slate-500">Intended database · TLS required</small></span><span className="rounded-full bg-sky-100 px-2 py-1 text-[7px] font-bold uppercase tracking-wide text-sky-800">Target</span></div>
      </section>
      <div className="hidden flex-col items-center justify-center text-slate-400 md:flex"><Github size={20}/><span className="my-2 h-12 w-px bg-slate-200"/><span className="text-[8px] font-bold uppercase tracking-wider">Source</span><span className="my-2 h-12 w-px bg-slate-200"/><ArrowRight size={16}/></div>
      <section aria-labelledby="web-flow-title" className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-sky-100 text-sky-800"><Globe2 size={19} aria-hidden="true"/></span><div><h2 id="web-flow-title" className="text-sm font-bold text-slate-950">Public project website</h2><p className="text-[9px] text-slate-500">Documentation and project overview</p></div></div>
        <div className="mt-6 grid gap-2">{[[Code2,'Next.js + React','App Router · TypeScript'],[Layers3,'Tailwind CSS','Responsive project pages'],[Server,'Static project content','No hospital database access']].map(([Icon,title,sub],index)=>{const Component=Icon as typeof Code2;return <div key={String(title)} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><span className="grid size-8 place-items-center rounded-lg bg-sky-50 text-sky-800"><Component size={16}/></span><span className="flex-1"><b className="block text-[11px]">{String(title)}</b><small className="mt-0.5 block text-[9px] text-slate-500">{String(sub)}</small></span><span className="text-[8px] text-slate-400">0{index+1}</span></div>;})}</div>
        <div className="my-4 flex items-center justify-center gap-2 text-[9px] text-slate-400"><span className="h-px flex-1 bg-slate-200"/><ArrowDown size={13}/><span className="h-px flex-1 bg-slate-200"/></div>
        <div className="flex items-center gap-3 rounded-xl bg-white p-3 ring-1 ring-slate-200"><span className="grid size-8 place-items-center rounded-lg bg-slate-950 text-white"><Globe2 size={15}/></span><span><b className="block text-[11px] text-slate-900">Vercel</b><small className="mt-0.5 block text-[9px] text-slate-500">Hosts this website only</small></span><span className="ml-auto rounded-full bg-emerald-50 px-2 py-1 text-[7px] font-bold uppercase tracking-wide text-emerald-800">Separate</span></div>
      </section>
    </div>
    <p className="mt-5 rounded-xl bg-amber-50 px-4 py-3 text-[10px] leading-5 text-amber-950"><b>Implementation note:</b> the Java source currently points to local MySQL and calls DAOs from UI panels. The diagram shows the intended PostgreSQL and service-layer architecture; those migration steps are not yet verified.</p>
  </div>;
}
