import Link from 'next/link';
import type { ReactNode } from 'react';
import { Activity, ArrowRight, ArrowUpRight, BedDouble, CalendarDays, Check, CircleHelp, ClipboardList, Github, ShieldCheck, Stethoscope, Users, Wallet } from 'lucide-react';
import { CtaSection } from '@/components/cta-section';
import { SectionHeading } from '@/components/page-intro';
import { StatusPill } from '@/components/status-pill';
import { repositoryUrl, technology } from '@/lib/site-data';

const highlights = [
  { icon: Users, name: 'Patient records', detail: 'Demographics and contact' },
  { icon: Stethoscope, name: 'Doctor directory', detail: 'Profiles and specialties' },
  { icon: CalendarDays, name: 'Appointments', detail: 'Patient and doctor visits' },
  { icon: BedDouble, name: 'Rooms & beds', detail: 'Availability and occupancy' },
  { icon: ClipboardList, name: 'Admissions', detail: 'Bed assignment and discharge' },
  { icon: Wallet, name: 'Billing', detail: 'Charges and payment state' },
];

export default function HomePage() {
  return <main id="main">
    <section className="mesh-bg relative overflow-hidden">
      <div className="pointer-events-none absolute -right-28 top-20 size-[500px] rounded-full border border-teal-100/80" /><div className="pointer-events-none absolute -right-6 top-44 size-[360px] rounded-full border border-dashed border-sky-200/70" />
      <div className="relative mx-auto grid max-w-[1280px] items-center gap-12 px-6 pb-16 pt-14 sm:pb-20 sm:pt-20 lg:grid-cols-[.92fr_1.08fr] lg:gap-14 lg:px-10 lg:pb-24 lg:pt-24">
        <div className="relative z-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-teal-100 bg-white/75 px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.14em] text-teal-800"><span className="size-1.5 rounded-full bg-emerald-500" /> JAVA DESKTOP · PROJECT PRESENTATION</div>
          <h1 className="text-balance mt-7 max-w-[650px] text-[43px] font-bold leading-[1.06] tracking-[-.06em] text-slate-950 sm:text-6xl lg:text-[68px]">Modern Hospital Management, <span className="text-teal-700">Built for Smarter Healthcare Operations</span></h1>
          <p className="mt-6 max-w-xl text-sm leading-7 text-slate-600 sm:text-base sm:leading-8">A Java Swing project bringing patient, doctor, appointment, admission, bed and billing workflows into a single desktop system—with a clear path toward PostgreSQL.</p>
          <div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/modules" className="inline-flex h-12 items-center gap-2 rounded-xl bg-teal-700 px-5 text-xs font-bold text-white shadow-lg shadow-teal-900/10 transition hover:-translate-y-0.5 hover:bg-teal-800">Explore system <ArrowRight size={15} aria-hidden="true" /></Link><Link href="/architecture" className="inline-flex h-12 items-center gap-2 rounded-xl border border-slate-200 bg-white/80 px-5 text-xs font-bold text-slate-700 transition hover:border-teal-200 hover:bg-white">View architecture <ArrowUpRight size={15} aria-hidden="true" /></Link><a href={repositoryUrl} target="_blank" rel="noreferrer" aria-label="Open project GitHub repository in a new tab" className="grid size-12 place-items-center rounded-xl border border-slate-200 bg-white/80 text-slate-700 transition hover:border-teal-200 hover:text-teal-800"><Github size={17} aria-hidden="true" /></a></div>
          <div className="mt-8 flex flex-wrap items-center gap-x-5 gap-y-2 text-[10px] text-slate-500"><span className="inline-flex items-center gap-1.5"><Check size={13} className="text-emerald-600" /> Existing desktop modules</span><span className="inline-flex items-center gap-1.5"><CircleHelp size={13} className="text-sky-700" /> PostgreSQL migration underway</span></div>
        </div>

        <div className="relative mx-auto w-full max-w-[620px] lg:ml-auto">
          <div className="absolute -left-5 top-10 z-10 hidden rounded-2xl border border-white bg-white/95 p-3 shadow-lg sm:block"><div className="grid size-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><ShieldCheck size={16} aria-hidden="true" /></div><p className="mt-2 text-[9px] font-bold text-slate-800">Project status</p><p className="mt-0.5 text-[8px] text-slate-500">Migration in progress</p></div>
          <div className="glass-panel relative overflow-hidden rounded-[24px] p-3 sm:p-4">
            <div className="flex h-10 items-center justify-between border-b border-slate-100 px-2"><div className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded-md bg-teal-700 text-white"><PlusIcon /></span><span className="text-[10px] font-bold text-slate-800">Care operations</span></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-emerald-50 px-2.5 py-1 text-[8px] font-semibold text-emerald-700 sm:inline-flex"><span className="mr-1.5 mt-0.5 size-1.5 rounded-full bg-emerald-500" />System overview</span><span className="grid size-6 place-items-center rounded-full bg-sky-100 text-[8px] font-bold text-sky-800">H</span></div></div>
            <div className="px-2 pb-3 pt-4"><p className="text-[8px] font-bold uppercase tracking-[.14em] text-slate-400">ILLUSTRATIVE UI PREVIEW</p><div className="mt-1 flex items-end justify-between"><h2 className="text-sm font-bold tracking-tight text-slate-900 sm:text-base">Hospital overview</h2><span className="text-[8px] text-slate-400">Concept · not a live screenshot</span></div>
              <div className="mt-4 grid grid-cols-3 gap-2"><PreviewStat label="Patients" icon={<Users size={13} />} /><PreviewStat label="Appointments" icon={<CalendarDays size={13} />} /><PreviewStat label="Available beds" icon={<BedDouble size={13} />} /></div>
              <div className="mt-2 grid gap-2 sm:grid-cols-[1.35fr_.9fr]"><div className="rounded-xl border border-slate-100 bg-white p-3"><div className="flex items-center justify-between"><p className="text-[9px] font-bold text-slate-800">Activity at a glance</p><span className="text-[8px] text-slate-400">Preview only</span></div><div className="mt-4 flex h-[118px] items-end gap-2 border-b border-l border-slate-100 px-2 pb-0"><span className="h-[34%] flex-1 rounded-t bg-teal-100"/><span className="h-[58%] flex-1 rounded-t bg-teal-200"/><span className="h-[43%] flex-1 rounded-t bg-teal-100"/><span className="h-[74%] flex-1 rounded-t bg-teal-300"/><span className="h-[54%] flex-1 rounded-t bg-teal-200"/><span className="h-[88%] flex-1 rounded-t bg-teal-500"/><span className="h-[67%] flex-1 rounded-t bg-teal-300"/><span className="h-[96%] flex-1 rounded-t bg-teal-600"/></div><div className="mt-2 flex justify-between text-[7px] text-slate-400"><span>Operational overview</span><span>Sample visualization</span></div></div><div className="rounded-xl border border-slate-100 bg-white p-3"><p className="text-[9px] font-bold text-slate-800">Workspace modules</p><ul className="mt-3 grid gap-2">{highlights.slice(0,4).map(({icon:Icon,name})=><li key={name} className="flex items-center gap-2 text-[8px] text-slate-600"><span className="grid size-6 place-items-center rounded-md bg-teal-50 text-teal-800"><Icon size={12} aria-hidden="true"/></span>{name}<ArrowUpRight size={10} className="ml-auto text-slate-300" aria-hidden="true"/></li>)}</ul><div className="mt-3 rounded-lg bg-sky-50 p-2 text-[8px] text-sky-900">Designed as a Java Swing desktop application</div></div></div>
            </div>
            <div className="flex items-center justify-between rounded-b-[18px] border-t border-slate-100 bg-slate-50/70 px-4 py-2.5"><span className="text-[8px] text-slate-500">Abstract product preview · no patient data</span><span className="text-[8px] font-semibold text-teal-800">Presentation website</span></div>
          </div>
          <div className="absolute -bottom-5 right-5 hidden items-center gap-2 rounded-xl border border-white bg-white p-3 shadow-lg sm:flex"><span className="grid size-8 place-items-center rounded-lg bg-sky-50 text-sky-800"><ActivityIcon /></span><span className="text-[9px] font-semibold text-slate-700">Java Swing <b className="text-slate-400">+</b> JDBC</span></div>
        </div>
      </div>
    </section>

    <section aria-label="Technology stack" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-[1280px] px-6 py-6 lg:px-10"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-slate-500">Two separate parts of one project</p><p className="text-[9px] text-slate-500">Status is labeled: desktop baseline vs migration target</p></div><div className="flex flex-wrap gap-2">{technology.map((item)=><span key={item.name} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 ${item.kind==='target'?'border-sky-100 bg-sky-50/60':'border-slate-200 bg-slate-50'}`}><span className={`size-1.5 rounded-full ${item.kind==='target'?'bg-sky-500':'bg-emerald-500'}`}/><b className="text-[10px] text-slate-800">{item.name}</b><small className="text-[8px] text-slate-500">{item.note}</small></span>)}</div></div></section>

    <section className="px-6 py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-[1280px] lg:px-4"><SectionHeading eyebrow="SYSTEM OVERVIEW" title="One place for the work around care." description="The desktop baseline covers core operations; security, reporting and the PostgreSQL transition are clearly marked as ongoing work."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{highlights.map(({icon:Icon,name,detail},index)=><Link href="/modules" key={name} className="group flex items-start gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_4px_16px_rgba(16,44,66,.03)] transition hover:-translate-y-0.5 hover:border-teal-200 hover:shadow-lg"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-sky-50 text-teal-800 transition group-hover:bg-teal-700 group-hover:text-white"><Icon size={19} aria-hidden="true"/></span><span className="min-w-0 flex-1"><small className="text-[9px] font-bold tracking-[.14em] text-slate-400">0{index+1}</small><b className="mt-1 block text-sm text-slate-900">{name}</b><span className="mt-1 block text-[11px] leading-5 text-slate-600">{detail}</span></span><ArrowUpRight size={14} className="mt-1 shrink-0 text-slate-300 group-hover:text-teal-700" aria-hidden="true"/></Link>)}</div><div className="mt-5 flex flex-wrap items-center gap-3 rounded-xl bg-amber-50 px-4 py-3 text-[10px] leading-5 text-amber-900"><span className="font-bold">Status note</span><span>Payments, reports, audit logs, notifications and expanded user management are roadmap items, not current features.</span></div></div></section>

    <section className="bg-slate-50 px-6 py-16 sm:py-20 lg:py-24"><div className="mx-auto grid max-w-[1280px] items-center gap-10 lg:grid-cols-2 lg:px-4"><div><SectionHeading eyebrow="BUILT WITH CLEAR BOUNDARIES" title="The desktop app remains the hospital system." description="Java Swing handles hospital workflows. PostgreSQL is the intended database destination. The Vercel site explains the project and has no connection to patient records."/><Link href="/architecture" className="inline-flex items-center gap-2 text-xs font-bold text-teal-800 hover:text-teal-950">Explore the architecture <ArrowRight size={14} aria-hidden="true"/></Link></div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><p className="text-[9px] font-bold uppercase tracking-[.15em] text-slate-500">MIGRATION STATUS</p><div className="mt-4 grid gap-3">{[['Desktop application','Java Swing · Existing project','Existing screens'],['Database','MySQL baseline → PostgreSQL target','Migration target'],['Public website','Next.js · Vercel hosting','Separate project site']].map(([title,description,status])=><div key={title} className="flex flex-col gap-3 rounded-xl border border-slate-100 bg-slate-50/70 p-4 sm:flex-row sm:items-center sm:justify-between"><span><b className="block text-xs text-slate-900">{title}</b><small className="mt-1 block text-[10px] text-slate-500">{description}</small></span><StatusPill status={status}/></div>)}</div></div></div></section>

    <section className="px-6 py-14 sm:py-18"><div className="mx-auto max-w-[1280px] lg:px-4"><SectionHeading eyebrow="ACADEMIC PROJECT" title="Built at Arya College of Engineering & I.T." description="Kukas, Jaipur · 5th Semester · Academic year 2026–27"/><div className="flex flex-wrap gap-3"><Link href="/team" className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-[11px] font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-800">Project information <ArrowRight size={14}/></Link><Link href="/docs" className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-200 px-4 text-[11px] font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-800">Documentation <ArrowRight size={14}/></Link></div></div></section>
    <CtaSection />
  </main>;
}

function PreviewStat({label,icon}:{label:string;icon:ReactNode}) { return <div className="rounded-xl border border-slate-100 bg-white p-2.5"><div className="flex items-center justify-between text-teal-700">{icon}<span className="text-[7px] font-semibold text-slate-400">TODAY</span></div><p className="mt-2 text-[8px] font-medium text-slate-500">{label}</p><p className="mt-0.5 text-xl font-bold tracking-tight text-slate-900">—</p></div>; }
function PlusIcon() { return <span aria-hidden="true" className="text-sm font-bold">+</span>; }
function ActivityIcon() { return <Activity size={15} aria-hidden="true"/>; }
