import Link from 'next/link';
import { ArrowRight, Github, Monitor } from 'lucide-react';
import { repositoryUrl } from '@/lib/site-data';

const modules = ['Patients', 'Doctors', 'Appointments', 'Admissions', 'Rooms & Beds', 'Billing & Payments', 'Reports', 'User Management', 'Settings', 'Notifications', 'Audit Logs'];

export default function HomePage() {
  return <main id="main">
    <section className="mesh-bg"><div className="mx-auto grid max-w-[1280px] items-center gap-10 px-6 py-16 sm:py-20 lg:grid-cols-[.9fr_1.1fr] lg:px-10 lg:py-24">
      <div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-teal-800">Hospital Management System</p><h1 className="mt-5 max-w-2xl text-balance text-4xl font-bold leading-[1.08] tracking-[-.055em] text-slate-950 sm:text-6xl">Professional hospital operations software.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-slate-600 sm:text-base sm:leading-8">An application for managing patients, doctors, appointments, admissions, rooms, beds, billing and hospital operations.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/product" className="inline-flex h-11 items-center gap-2 rounded-lg bg-teal-700 px-4 text-xs font-bold text-white">Explore the product <ArrowRight size={14}/></Link><a href={repositoryUrl} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-700"><Github size={15}/>GitHub</a></div></div>
      <div className="grid min-h-[300px] place-items-center rounded-2xl border border-slate-200 bg-white/75 p-8 text-center shadow-sm sm:min-h-[350px]"><div><span className="mx-auto grid size-14 place-items-center rounded-xl bg-teal-50 text-teal-800"><Monitor size={25}/></span><p className="mt-5 text-sm font-semibold text-slate-700">Real application screenshots will appear here after the corresponding Java screens are completed.</p></div></div>
    </div></section>
    <section className="border-y border-amber-200 bg-amber-50"><div className="mx-auto flex max-w-[1280px] items-center gap-3 px-6 py-4 text-xs font-semibold text-amber-950 lg:px-10"><span className="size-2 rounded-full bg-amber-500"/>Application interface currently under development.</div></section>
    <section className="mx-auto max-w-[1280px] px-6 py-14 sm:py-16 lg:px-10"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-teal-800">Product areas</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-slate-950">Application under development</h2><p className="mt-3 text-sm leading-7 text-slate-600">We are building the Hospital Management System screen-by-screen with connected database operations, authentication, validation, security and real application workflows.</p></div><ul className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map((name)=><li key={name} className="flex items-center gap-3 border-t border-slate-200 py-4 text-sm font-medium text-slate-700"><span className="size-2 rounded-full bg-teal-600"/>{name}</li>)}</ul><p className="mt-5 text-xs text-slate-500">These are planned product areas. Availability depends on implementation of each application module.</p><Link href="/modules" className="mt-6 inline-flex items-center gap-2 text-xs font-bold text-teal-800">View product areas <ArrowRight size={14}/></Link></section>
  </main>;
}
