import type { Metadata } from 'next';
import { ArrowUpRight, Github, Mail, MessageCircle } from 'lucide-react';
import { PageIntro } from '@/components/page-intro';
import { repositoryUrl } from '@/lib/site-data';

export const metadata: Metadata = { title: 'Contact & request a demo', description: 'Contact the Hospital Management System team to discuss product workflows and request a demonstration.' };

export default function ContactPage() {
  return <main id="main"><PageIntro eyebrow="CONTACT & DEMO" title="Let’s discuss your hospital’s workflow." description="Share the workflows you want to explore. Contact options below open directly; this site does not collect or submit your information."/><section className="mx-auto grid max-w-[1120px] gap-5 px-5 py-12 sm:grid-cols-2 sm:px-8 sm:py-16 lg:px-12"><article className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><span className="grid size-11 place-items-center rounded-xl bg-white/10 text-teal-200"><MessageCircle size={20}/></span><h2 className="mt-5 text-xl font-bold">Discuss your requirements</h2><p className="mt-3 text-xs leading-6 text-slate-300">No demo-request service or public product email is configured yet. Use GitHub to contact the maintainers, or include your preferred contact details in an issue.</p><a href={repositoryUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-white px-4 py-3 text-xs font-bold text-slate-900"><Github size={15}/>Open GitHub repository <ArrowUpRight size={14}/></a></article><article className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><span className="grid size-11 place-items-center rounded-xl bg-sky-50 text-sky-800"><Mail size={20}/></span><h2 className="mt-5 text-xl font-bold text-slate-950">Request a product conversation</h2><p className="mt-3 text-xs leading-6 text-slate-600">For now, repository discussions are the verified public contact path. A contact form can be added once a secure submission endpoint and response owner are available.</p><a href={repositoryUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-teal-800">Visit repository discussions <ArrowUpRight size={14}/></a></article></section></main>;
}
