-- Initial PostgreSQL schema for a NEW, EMPTY hospital_management database.
-- This file intentionally contains no DROP, TRUNCATE, or legacy-password copy.
-- Confirm column definitions and constraints against the original MySQL dump
-- before using this as a production migration target.

CREATE TABLE patients (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    gender VARCHAR(40),
    date_of_birth DATE,
    phone VARCHAR(40),
    email VARCHAR(254),
    address TEXT,
    blood_group VARCHAR(8),
    emergency_contact VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE doctors (
    doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    specialization VARCHAR(120),
    phone VARCHAR(40),
    email VARCHAR(254),
    experience INTEGER CHECK (experience IS NULL OR experience >= 0),
    consultation_fee NUMERIC(12, 2) CHECK (consultation_fee IS NULL OR consultation_fee >= 0),
    availability VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(40) NOT NULL UNIQUE,
    room_type VARCHAR(80),
    price_per_day NUMERIC(12, 2) NOT NULL CHECK (price_per_day >= 0)
);

CREATE TABLE beds (
    bed_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL REFERENCES rooms(room_id) ON DELETE RESTRICT,
    bed_number VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE'
        CHECK (status IN ('AVAILABLE', 'OCCUPIED')),
    UNIQUE (room_id, bed_number)
);

CREATE TABLE admissions (
    admission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(patient_id) ON DELETE RESTRICT,
    bed_id INTEGER NOT NULL REFERENCES beds(bed_id) ON DELETE RESTRICT,
    admission_date DATE NOT NULL,
    discharge_date DATE,
    CHECK (discharge_date IS NULL OR discharge_date >= admission_date)
);

CREATE TABLE appointments (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(patient_id) ON DELETE RESTRICT,
    doctor_id INTEGER NOT NULL REFERENCES doctors(doctor_id) ON DELETE RESTRICT,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    reason TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING'
);

CREATE TABLE bills (
    bill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(patient_id) ON DELETE RESTRICT,
    admission_id INTEGER REFERENCES admissions(admission_id) ON DELETE RESTRICT,
    room_charges NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (room_charges >= 0),
    doctor_charges NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (doctor_charges >= 0),
    medicine_charges NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (medicine_charges >= 0),
    other_charges NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (other_charges >= 0),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    paid_amount NUMERIC(12, 2) NOT NULL DEFAULT 0
        CHECK (paid_amount >= 0 AND paid_amount <= total_amount),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (payment_status IN ('PENDING', 'PARTIAL', 'PAID')),
    bill_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Retained as an independent legacy entity until invoice/bill consolidation
-- is explicitly designed. Its exact legacy definition was not present in the
-- supplied schema facts; columns below reflect those facts and require dump review.
CREATE TABLE invoices (
    invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL REFERENCES patients(patient_id) ON DELETE RESTRICT,
    consultation_fee NUMERIC(12, 2),
    room_charges NUMERIC(12, 2),
    medicine_charges NUMERIC(12, 2),
    lab_charges NUMERIC(12, 2),
    total_amount NUMERIC(12, 2),
    payment_status VARCHAR(40),
    invoice_date TIMESTAMPTZ
);

-- Existing MySQL passwords are intentionally not represented here. Imported
-- identities start PENDING and must receive a new BCrypt hash through the
-- secure account provisioning flow before they can become ACTIVE.
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(254) UNIQUE,
    password_hash VARCHAR(100),
    full_name VARCHAR(150),
    phone VARCHAR(40),
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'RECEPTIONIST', 'DOCTOR', 'ACCOUNTANT')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
    locked_until TIMESTAMPTZ,
    created_by INTEGER REFERENCES users(user_id) ON DELETE RESTRICT,
    updated_by INTEGER REFERENCES users(user_id) ON DELETE RESTRICT,
    CHECK (status <> 'ACTIVE' OR password_hash IS NOT NULL)
);

CREATE INDEX idx_patients_name ON patients(name);
CREATE INDEX idx_patients_phone ON patients(phone);
CREATE INDEX idx_patients_email ON patients(email);
CREATE INDEX idx_doctors_name ON doctors(name);
CREATE INDEX idx_doctors_specialization ON doctors(specialization);
CREATE INDEX idx_beds_room_id ON beds(room_id);
CREATE INDEX idx_beds_status ON beds(status);
CREATE INDEX idx_admissions_patient_id ON admissions(patient_id);
CREATE INDEX idx_admissions_bed_id ON admissions(bed_id);
CREATE INDEX idx_admissions_discharge_date ON admissions(discharge_date);
CREATE UNIQUE INDEX uq_admissions_one_active_per_bed
    ON admissions(bed_id) WHERE discharge_date IS NULL;
CREATE INDEX idx_appointments_patient_id ON appointments(patient_id);
CREATE INDEX idx_appointments_doctor_id ON appointments(doctor_id);
CREATE INDEX idx_appointments_date ON appointments(appointment_date);
CREATE INDEX idx_bills_patient_id ON bills(patient_id);
CREATE INDEX idx_bills_admission_id ON bills(admission_id);
CREATE INDEX idx_bills_payment_status ON bills(payment_status);
