-- Additive, re-runnable authentication foundation for PostgreSQL.
-- This migration never drops data. Apply after 001_initial_schema.sql.

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(40) NOT NULL DEFAULT '',
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'RECEPTIONIST', 'DOCTOR', 'ACCOUNTANT')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
    locked_until TIMESTAMPTZ,
    created_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT,
    updated_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT,
    CHECK (status <> 'ACTIVE' OR length(password_hash) = 60)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    event_type VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower ON users (lower(email));
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_created ON audit_logs (user_id, created_at DESC);

-- Safe additions for installations that created the earlier draft table before
-- all authentication columns were present. Existing values are never rewritten.
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
