-- Additive patient authentication identities linked to existing clinical records.
-- No patient records are changed, copied, or deleted by this migration.
CREATE TABLE IF NOT EXISTS patient_credentials (
    patient_credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL UNIQUE REFERENCES patients(patient_id) ON DELETE RESTRICT,
    username VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING')),
    failed_login_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_attempts >= 0),
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMPTZ,
    CHECK (status <> 'ACTIVE' OR length(password_hash) = 60)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_patient_credentials_username_lower
    ON patient_credentials (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_patient_credentials_email_lower
    ON patient_credentials (lower(email));
CREATE INDEX IF NOT EXISTS idx_patient_credentials_status ON patient_credentials(status);
