import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Github, HeartPulse, ShieldCheck } from 'lucide-react';
import { PageIntro } from '@/components/page-intro';
import { repositoryUrl } from '@/lib/site-data';

export const metadata: Metadata = { title: 'About the system', description: 'About the Hospital Management System product and its public source repository.' };

export default function AboutPage() {
  return <main id="main"><PageIntro eyebrow="ABOUT THE SYSTEM" title="Technology for connected hospital operations." description="Hospital Management System is a Java desktop application focused on organizing the essential administrative workflows that support care delivery."/><section className="mx-auto grid max-w-[1100px] gap-4 px-5 py-12 sm:grid-cols-2 sm:px-8 sm:py-16 lg:px-12"><article className="rounded-2xl border border-slate-200 p-6"><span className="grid size-11 place-items-center rounded-xl bg-teal-50 text-teal-800"><HeartPulse size={20}/></span><h2 className="mt-4 text-base font-bold text-slate-950">A connected operations platform</h2><p className="mt-2 text-xs leading-6 text-slate-600">The desktop system brings patient, doctor, appointment, admission, room, bed and billing workflows into one application.</p></article><article className="rounded-2xl border border-slate-200 p-6"><span className="grid size-11 place-items-center rounded-xl bg-sky-50 text-sky-800"><ShieldCheck size={20}/></span><h2 className="mt-4 text-base font-bold text-slate-950">Honest about system readiness</h2><p className="mt-2 text-xs leading-6 text-slate-600">This site documents application capabilities, architecture and known release prerequisites without implying unverified deployment or certifications.</p></article><div className="rounded-2xl bg-slate-950 p-6 text-white sm:col-span-2"><h2 className="text-base font-bold">Source and product information</h2><p className="mt-2 text-xs leading-6 text-slate-300">Review the source repository or get in touch to discuss the current product scope.</p><div className="mt-5 flex flex-wrap gap-3"><a href={repositoryUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-3 text-xs font-bold text-slate-900"><Github size={15}/>Source repository</a><Link href="/contact" className="inline-flex items-center gap-2 rounded-lg border border-white/20 px-4 py-3 text-xs font-semibold text-white">Contact <ArrowRight size={14}/></Link></div></div></section></main>;
}
