import type { Metadata } from 'next';
import { PageIntro } from '@/components/page-intro';

export const metadata: Metadata = { title: 'Architecture', description: 'The Java desktop architecture of the Hospital Management System.' };

const applicationStack = ['Java 17+', 'Java Swing + FlatLaf', 'Service Layer', 'DAO Layer', 'JDBC + HikariCP', 'PostgreSQL'];

export default function ArchitecturePage() {
  return <main id="main"><PageIntro eyebrow="APPLICATION ARCHITECTURE" title="A Java desktop hospital management system." description="The HMS is a Java Swing desktop application. The Next.js website is a separate product-information site and does not provide the hospital workflows."/><section className="mx-auto max-w-[1280px] px-6 py-12 lg:px-10"><h2 className="text-base font-semibold text-slate-900">Application stack</h2><ol className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{applicationStack.map((item,index)=><li key={item} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white p-4 text-sm font-medium text-slate-700"><span className="grid size-7 place-items-center rounded-full bg-teal-50 text-xs font-bold text-teal-800">{index+1}</span>{item}</li>)}</ol><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">Application design</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600"><li>BCrypt authentication and role-based authorization</li><li>Prepared SQL statements and transactional database operations</li><li>Environment-based database configuration</li></ul></article><article className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-semibold text-slate-900">PostgreSQL setup</h2><p className="mt-3 text-sm leading-6 text-slate-600">The repository includes PostgreSQL schema and migrations plus HikariCP connection pooling. A configured development environment is documented separately; the public website is not part of this runtime architecture.</p></article></div></section></main>;
}
